#ifndef _NAVIGATOR_RES_H_
#define _NAVIGATOR_RES_H_

#define IDC_MLEDIT      104
#define IDC_NAVIGATOR   105
#define IDC_NAVIGATOR_TAB	106
#define IDC_NAVIGATOR_PAGE1	107
#define IDC_NAVIGATOR_PAGE2	108
#define IDC_NAVIGATOR_PAGE3	109
#define IDC_NAVIGATOR_PAGE4	110

#endif
